const $=id=>document.getElementById(id);
const send=async(action,data={})=>{const result=await chrome.runtime.sendMessage({action,...data});if(result.error)throw new Error(result.error);return result.result;};
function notice(message){$('status').textContent=message;}
$('installed-version').textContent='v'+chrome.runtime.getManifest().version;
$('check-login').onclick=async()=>{const button=$('check-login');button.disabled=true;try{const result=await send('login-status');$('session-status').textContent=result.sites.map(site=>`${site.source==='divar'?'دیوار':'شیپور'}: ${site.message}`).join('\n');}catch(error){$('session-status').textContent=error.message;}finally{button.disabled=false;}};
for(const name of ['login','search'])$(name).onsubmit=async event=>{
  event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));const button=form.querySelector('button');button.disabled=true;
  try{await send(name,data);if(name==='login')form.elements.phone.value='';notice(name==='login'?'فرم سایت باز می‌شود؛ کد را در سایت وارد کن.':'جست‌وجو شروع شد؛ پیشرفت در افزونه و پنل نمایش داده می‌شود.');}catch(error){notice(error.message);}finally{button.disabled=false;}
};
for(const name of ['options','dashboard','stop','resume'])$(name).onclick=async()=>{try{await send(name);}catch(error){notice(error.message);}};
async function refresh(){const state=await chrome.storage.local.get(['captureJob','loginState-divar','loginState-sheypoor','searchError','leadRadarToken','leadRadarEndpoint']);const job=state.captureJob;$('connection').textContent=state.leadRadarToken?`متصل به ${state.leadRadarEndpoint==='http://127.0.0.1:4300'?'پنل محلی':'پنل ابری'}`:'اتصال تنظیم نشده؛ «تنظیم اتصال» را بزن.';$('progress').textContent=job?`${job.source==='divar'?'دیوار':'شیپور'} · ${job.topic} · ${job.processed}/${job.total}\n${job.message}`:'هنوز صفی آغاز نشده است.';$('run-progress').hidden=!job;$('run-progress').max=Math.max(1,Number(job?.total)||1);$('run-progress').value=Math.max(0,Number(job?.processed)||0);$('resume').hidden=job?.status!=='paused';$('stop').hidden=!['running','paused'].includes(job?.status);$('login-state').textContent=['divar','sheypoor'].map(s=>state[`loginState-${s}`]?`${s==='divar'?'دیوار':'شیپور'}: ${state[`loginState-${s}`].message}`:'').filter(Boolean).join('\n');if(state.searchError)notice(state.searchError);}
chrome.storage.onChanged.addListener(()=>void refresh());void refresh();
