import { useRef, useState } from 'react';
import { RotateCcw, Trash2 } from 'lucide-react';
export default function DataResetControls({localMode,onChanged}:{localMode:boolean;onChanged:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [text,setText]=useState('');const [scope,setScope]=useState(localMode?'all':'browser');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [dialogOpen,setDialogOpen]=useState(false);const [deleted,setDeleted]=useState<string[]>([]);
  const act=async(restore=false)=>{setBusy(true);setMessage('');try{
    const bases=restore&&deleted.length?deleted:localMode&&scope==='all'?['/api/companion','/api']:[localMode&&scope==='browser'?'/api/companion':'/api'];
    if(!restore)for(const base of bases){const response=await fetch(`${base}/data/status`);const data=await response.json();if(!response.ok)throw new Error(data.error||'بررسی بانک ممکن نشد؛ هیچ بانکی حذف نشد.');if(data.active)throw new Error('ابتدا اجراهای فعال یا متوقف‌شده را لغو کن؛ هیچ بانکی حذف نشد.');}
    const completed:string[]=[];
    try{for(const base of bases){const response=await fetch(`${base}/data/${restore?'restore':'reset'}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true,confirmText:text})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(data.changed)completed.push(base);}}
    catch(error){if(completed.length){setDeleted(restore?bases.filter(base=>!completed.includes(base)):completed);onChanged();throw new Error('عملیات یک بانک انجام شد، اما بانک دیگر کامل نشد؛ باقی عملیات و بازیابی حذف در دسترس است. '+(error instanceof Error?error.message:''));}throw error;}
    setDeleted(restore?[]:completed);setMessage(restore?'آخرین حذف کامل بازیابی شد.':'بانک‌های انتخاب‌شده خالی شدند؛ بازیابی آخرین حذف در دسترس است.');dialog.current?.close();setText('');onChanged();
  }catch(error){setMessage(error instanceof Error?error.message:'حذف ممکن نشد.');}finally{setBusy(false);}};
  return <div className="reset-controls"><select disabled={busy||dialogOpen} aria-label="بانک موردنظر برای حذف همه" value={scope} onChange={event=>setScope(event.target.value)}>{localMode&&<option value="all">همهٔ بانک‌ها: رادار، دیوار و شیپور</option>}<option value="browser">{localMode?'فقط دیوار و شیپور محلی':'کل بانک رادار، دیوار و شیپور'}</option>{localMode&&<option value="radar">فقط رادار اصلی و پویش‌ها</option>}</select><button disabled={busy} className="ghost-button danger-button" onClick={()=>{setText('');setMessage('');setDialogOpen(true);dialog.current?.showModal();}}><Trash2 size={16}/> حذف همهٔ اطلاعات</button><button disabled={busy} className="ghost-button" onClick={()=>void act(true)}><RotateCcw size={16}/> بازیابی آخرین حذف</button>{message&&<p role="status">{message}</p>}<dialog ref={dialog} className="history-confirm-dialog" aria-labelledby="reset-title" onCancel={event=>{if(busy)event.preventDefault();}} onClose={()=>setDialogOpen(false)}><form onSubmit={event=>{event.preventDefault();void act();}}><h2 id="reset-title">حذف همهٔ اطلاعات</h2><p>{localMode&&scope==='all'?'تمام اطلاعات هر دو بانک محلی: رادار، دیوار و شیپور':localMode&&scope==='browser'?'تمام آگهی‌ها، شماره‌ها و تاریخچهٔ دیوار و شیپور محلی':'تمام سرنخ‌ها، آگهی‌ها، شماره‌ها، پویش‌ها و تاریخچهٔ رادار'} حذف می‌شوند. آخرین حذف کامل قابل بازیابی است. ورود سایت‌ها و تنظیمات حفظ می‌شوند.</p><label>عبارت «من تایید میکنم» را بنویس<input disabled={busy} autoComplete="off" value={text} onChange={event=>setText(event.target.value)} autoFocus/></label>{message&&<p role="alert">{message}</p>}<div className="history-actions"><button type="button" className="ghost-button" disabled={busy} onClick={()=>dialog.current?.close()}>انصراف</button><button className="ghost-button danger-button" disabled={busy||text!=='من تایید میکنم'}>{busy?'در حال انجام…':'حذف همهٔ اطلاعات'}</button></div></form></dialog></div>;
}
