import { useRef, useState } from 'react';
import { RotateCcw, Trash2 } from 'lucide-react';
export default function DataResetControls({localMode,onChanged}:{localMode:boolean;onChanged:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [text,setText]=useState('');const [scope,setScope]=useState('browser');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const act=async(restore=false)=>{setBusy(true);setMessage('');try{
    const base=localMode&&scope==='browser'?'/api/companion':'/api';
    const response=await fetch(`${base}/data/${restore?'restore':'reset'}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true,confirmText:text})});const data=await response.json();if(!response.ok)throw new Error(data.error);
    setMessage(restore?'آخرین حذف کامل بازیابی شد.':'بانک انتخاب‌شده خالی شد؛ بازیابی آخرین حذف در دسترس است.');dialog.current?.close();setText('');onChanged();
  }catch(error){setMessage(error instanceof Error?error.message:'حذف ممکن نشد.');}finally{setBusy(false);}};
  return <div className="reset-controls"><select aria-label="بانک موردنظر برای حذف همه" value={scope} onChange={event=>setScope(event.target.value)}><option value="browser">{localMode?'آگهی‌های دیوار و شیپور محلی':'کل بانک رادار، دیوار و شیپور'}</option>{localMode&&<option value="radar">بانک رادار اصلی و پویش‌ها</option>}</select><button className="ghost-button danger-button" onClick={()=>{setText('');setMessage('');dialog.current?.showModal();}}><Trash2 size={16}/> حذف همهٔ داده‌های بانک</button><button disabled={busy} className="ghost-button" onClick={()=>void act(true)}><RotateCcw size={16}/> بازیابی آخرین حذف</button>{message&&<p role="status">{message}</p>}<dialog ref={dialog} className="history-confirm-dialog" aria-labelledby="reset-title"><form onSubmit={event=>{event.preventDefault();void act();}}><h2 id="reset-title">حذف همهٔ اطلاعات</h2><p>{localMode&&scope==='browser'?'تمام آگهی‌ها، شماره‌ها و تاریخچهٔ دیوار و شیپور محلی':'تمام سرنخ‌ها، آگهی‌ها، شماره‌ها، پویش‌ها و تاریخچهٔ رادار'} حذف می‌شوند. آخرین حذف کامل قابل بازیابی است.</p><label>عبارت «من تایید میکنم» را بنویس<input autoComplete="off" value={text} onChange={event=>setText(event.target.value)} autoFocus/></label>{message&&<p role="alert">{message}</p>}<div className="history-actions"><button type="button" className="ghost-button" disabled={busy} onClick={()=>dialog.current?.close()}>انصراف</button><button className="ghost-button danger-button" disabled={busy||text!=='من تایید میکنم'}>حذف همهٔ اطلاعات</button></div></form></dialog></div>;
}
