import {useRef,useState} from 'react';
import {Trash2,RotateCcw} from 'lucide-react';

export default function LeadBankCleanup({onChanged}:{onChanged:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  async function act(restore=false){setBusy(true);setMessage('');try{
    const response=await fetch(`/api/leads/bank/${restore?'restore':'clear'}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:true,confirmText:text})});const data=await response.json();if(!response.ok)throw new Error(data.error||'تغییر بانک ممکن نشد.');
    setMessage(`${Number(data.changed).toLocaleString('fa-IR')} سرنخ ${restore?'بازیابی':'حذف'} شد.`);dialog.current?.close();setText('');onChanged();
  }catch(error){setMessage(error instanceof Error?error.message:'عملیات انجام نشد.');}finally{setBusy(false);}}
  return <section className="panel lead-bank-cleanup"><div><h3>پاک‌سازی بانک سرنخ‌ها</h3><p>فقط سرنخ‌های منابع عمومی حذف می‌شوند؛ پویش‌ها و بانک دیوار و شیپور حفظ می‌شوند. آخرین پاک‌سازی قابل بازیابی است.</p></div><div className="history-actions"><button className="ghost-button danger-button" disabled={busy} onClick={()=>{setText('');setMessage('');dialog.current?.showModal();}}><Trash2 size={16}/> پاک‌کردن کل بانک سرنخ‌ها</button><button className="ghost-button" disabled={busy} onClick={()=>void act(true)}><RotateCcw size={16}/> بازیابی آخرین پاک‌سازی</button></div>{message&&<p role="status">{message}</p>}<dialog ref={dialog} className="history-confirm-dialog" aria-labelledby="lead-cleanup-title" onCancel={event=>{if(busy)event.preventDefault();}}><form onSubmit={event=>{event.preventDefault();void act();}}><h2 id="lead-cleanup-title">پاک‌کردن کل بانک سرنخ‌ها</h2><p>تمام سرنخ‌های عمومی همهٔ پویش‌ها حذف می‌شوند، نه فقط نتایج فیلتر فعلی. هیچ آگهیِ دیوار یا شیپور حذف نمی‌شود.</p><label>عبارت «من تایید میکنم» را بنویس<input disabled={busy} value={text} onChange={event=>setText(event.target.value)} autoComplete="off" autoFocus/></label>{message&&<p role="alert">{message}</p>}<div className="history-actions"><button type="button" className="ghost-button" disabled={busy} onClick={()=>dialog.current?.close()}>انصراف</button><button className="ghost-button danger-button" disabled={busy||text!=='من تایید میکنم'}>{busy?'در حال پاک‌سازی…':'تأیید پاک‌سازی'}</button></div></form></dialog></section>;
}
