import { useEffect, useState } from 'react';
import { Download, Play, Radar, Phone, Square, RefreshCw } from 'lucide-react';
import CloudCaptureView from './CloudCaptureView';
import DataResetControls from './DataResetControls';
import { browserCommand } from './browser-bridge';
import type { Lead } from '../shared/types';

type Runtime={local:boolean};
const cities=[['iran','کل ایران'],['tehran','تهران'],['qazvin','قزوین'],['rasht','رشت'],['karaj','کرج'],['mashhad','مشهد'],['isfahan','اصفهان'],['shiraz','شیراز'],['tabriz','تبریز'],['qom','قم'],['ahvaz','اهواز']];
async function api<T=unknown>(path:string,body?:unknown):Promise<T>{const res=await fetch(path,{method:body?'POST':'GET',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error||'ارتباط ممکن نشد.');return data as T;}
export default function RadarWorkspace({onPublicSearch,onChanged,publicLeads,campaignId}:{onPublicSearch:(topic:string,city:string)=>Promise<void>;onChanged:()=>void;publicLeads:Lead[];campaignId:number|null}){
  const [runtime,setRuntime]=useState<Runtime|null>(null);const [connected,setConnected]=useState(false);const [topic,setTopic]=useState('');const [city,setCity]=useState('iran');const [source,setSource]=useState('divar');const [url,setUrl]=useState('');const [limit,setLimit]=useState(20);const [phone,setPhone]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [progress,setProgress]=useState('');const [version,setVersion]=useState(0);
  useEffect(()=>{void api<Runtime>('/api/runtime').then(setRuntime).catch(error=>setMessage(error.message));},[]);
  useEffect(()=>{if(!runtime)return;let alive=true;const refresh=async()=>{try{if(runtime.local){const state=await api('/api/companion/state');if(alive)setConnected(Boolean(state));const runs=await api<Array<{message:string;status:string}>>('/api/companion/capture-runs');if(alive)setProgress(runs[0]?.message||'آمادهٔ جست‌وجو');}else{const state=await browserCommand<{connected:boolean;job?:{message:string}}>('status');if(alive){setConnected(state.connected);setProgress(state.job?.message||'آمادهٔ جست‌وجو');}}}catch{if(alive)setConnected(false);}};void refresh();const timer=window.setInterval(()=>void refresh(),5000);return()=>{alive=false;window.clearInterval(timer);};},[runtime]);
  const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();}catch(error){setMessage(error instanceof Error?error.message:'درخواست انجام نشد.');}finally{setBusy(false);}};
  const launch=async()=>{
    if(source==='public'){await onPublicSearch(topic,cities.find(c=>c[0]===city)?.[1]||'کل ایران');return;}
    if(!runtime)throw new Error('در حال آماده‌سازی پنل');
    if(runtime.local){const result=await api<{url:string;tabs:Array<{index:number;url:string}>}>(`/api/companion/browser/${source}/${url?'navigate':'search'}`,url?{url}:{topic,city:cities.find(c=>c[0]===city)?.[1]||'کل ایران'});const index=result.tabs.find(tab=>tab.url===result.url)?.index;
      if(index===undefined)throw new Error('برگهٔ جست‌وجو پیدا نشد.');await api(`/api/companion/browser/${source}/extract`,{tabIndex:index,limit});
    }else await browserCommand('search',{source,topic,city,url,limit});setMessage('جست‌وجو و استخراج شروع شد؛ نتیجه و اکسل پایین همین صفحه به‌روز می‌شوند.');setVersion(v=>v+1);
  };
  const login=async()=>{if(runtime?.local){const results=await Promise.allSettled(['divar','sheypoor'].map(site=>api(`/api/companion/browser/${site}/login`,{phone})));const errors=results.filter(r=>r.status==='rejected') as PromiseRejectedResult[];if(errors.length)throw new Error(errors.map(r=>r.reason.message).join(' · '));}else await browserCommand('login',{source:'both',phone});setPhone('');setMessage('فرم ورود سایت‌ها آماده می‌شود؛ کد پیامکی را در همان برگه وارد کن.');};
  const stop=async()=>{if(source==='public'){const runs=await api<Array<{id:number;status:string}>>('/api/runs');for(const run of runs.filter(r=>['running','queued'].includes(r.status)))await api(`/api/runs/${run.id}/cancel`,{});onChanged();}else if(runtime?.local){const runs=await api<Array<{id:string;status:string}>>('/api/companion/capture-runs');for(const run of runs.filter(r=>['running','paused'].includes(r.status)))await api(`/api/companion/capture-runs/${run.id}/cancel`,{});}else await browserCommand('stop');setMessage('درخواست توقف ارسال شد.');};
  return <div className="radar-workspace"><section className="radar-hero"><div className="radar-kicker"><Radar size={18}/> رادار یکپارچهٔ بازار ایران <span className={connected?'connected':''}>{connected?'مرورگر متصل':'نیازمند اتصال مرورگر'}</span></div><h1>جست‌وجو کن. بررسی کن. اکسل بگیر.</h1><p>دیوار، شیپور و منابع عمومی در یک فضای کاری؛ هر جست‌وجو با نتایج مستقل.</p><form className="radar-launch" onSubmit={event=>{event.preventDefault();void perform(launch);}}><label>موضوع<input value={topic} onChange={event=>setTopic(event.target.value)} required minLength={2} placeholder="مثلاً موبایل، دوچرخه یا کابینت"/></label><label>شهر<select value={city} onChange={event=>setCity(event.target.value)}>{cities.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>منبع<select value={source} onChange={event=>setSource(event.target.value)}><option value="divar">دیوار</option><option value="sheypoor">شیپور</option><option value="public">منابع عمومی رادار</option></select></label><button className="primary-button" disabled={busy||!runtime}><Play size={18}/> جست‌وجو و استخراج</button><details><summary>فیلترهای بیشتر</summary><label>تعداد آگهی<input type="number" min={1} max={40} value={limit} onChange={event=>setLimit(Number(event.target.value))}/></label><label>لینک جست‌وجوی فیلترشده<input type="url" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://divar.ir/s/..."/></label></details></form><div className="radar-progress" role="status"><span>{progress||'در حال بررسی اتصال…'}</span><button className="ghost-button" disabled={busy} onClick={()=>void perform(stop)}><Square size={14}/> توقف</button>{!runtime?.local&&<button className="ghost-button" disabled={busy} onClick={()=>void perform(async()=>{await browserCommand('resume');})}><RefreshCw size={14}/> ادامه</button>}</div>{message&&<p className="radar-message" role="status">{message}</p>}</section>
    <details className="panel radar-login"><summary><Phone size={16}/> ورود به دیوار و شیپور</summary><form onSubmit={event=>{event.preventDefault();void perform(login);}}><label>شمارهٔ همراه خودت<input type="tel" inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)} required autoComplete="tel" placeholder="0912…"/></label><button className="primary-button" disabled={busy}>آماده‌کردن ورود هر دو سایت</button><p>کد پیامکی را در برگهٔ اصلی سایت وارد کن؛ نشست ورود در مرورگرت می‌ماند.</p></form></details>
    {!connected&&<div className="radar-connect panel"><p>{runtime?.local?'همراه محلی را با npm run companion اجرا کن.':'افزونهٔ ۲.۱ را نصب کن، صفحه را تازه کن و در بخش اتصال پایین، کلید اتصال بساز.'}</p><a className="primary-button" href="/lead-radar-extension.zip" download><Download size={16}/> دانلود افزونه</a></div>}
    <details className="panel radar-cleanup"><summary>مدیریت بانک و حذف همهٔ اطلاعات</summary><DataResetControls localMode={Boolean(runtime?.local)} onChanged={()=>{setVersion(v=>v+1);onChanged();}}/></details>
    {source==='public'?<section className="panel public-results"><div className="capture-results-heading"><h2>نتایج منابع عمومی ({publicLeads.length.toLocaleString('fa-IR')})</h2><a className="primary-button" href={`/api/export.xlsx${campaignId?`?campaignId=${campaignId}`:''}`}><Download size={16}/> دریافت اکسل</a></div>{publicLeads.length?publicLeads.map(lead=><article key={lead.id}><div><h3>{lead.title}</h3><span>{lead.city} · {lead.source}</span></div><a href={`tel:${lead.phone}`} dir="ltr">{lead.phone}</a><a href={lead.url} target="_blank" rel="noreferrer">مشاهدهٔ آگهی</a></article>):<p>نتایج این پویش پس از دریافت صفحات اینجا ظاهر می‌شوند.</p>}</section>:runtime&&<CloudCaptureView key={`${runtime.local}:${version}`} localMode={runtime.local}/>}
  </div>;
}
